### ISSUE TITLE
Support for Sonoff 4ch Pro & Sonoff 4CH Pro R2 

### ISSUE THREAD

**Issue by LyoshaDovolen** [robertklep/name.klep.sonoff#11]
Support for Sonoff 4ch Pro & Sonoff 4CH Pro R2 
https://www.itead.cc/smart-home/sonoff-4ch-pro.html

**Comment by robertklep** [comment]
The current beta version of the app should support the 4CH and 4CH Pro devices, provided that they are running the Tasmota firmware (and have the correct module type set).

The devices will likely never be supported when they run the original firmware (because recent versions of that firmware make it impossible to pair with Homey).

**Comment by LyoshaDovolen** [comment]
i need click [this](https://sun9-7.userapi.com/c840435/v840435896/816a4/SqHFvo83TNc.jpg) for install 4ch pro?

**Comment by robertklep** [comment]
Yes, that should be it. But make sure that the Tasmota module type is set correctly, which you can do from the Tasmota configuration page of your device (showing the page of a Sonoff TH because I don't have a 4CH available, but the page is the same):

<img width="413" alt="screen shot 2018-05-10 at 11 50 02" src="https://user-images.githubusercontent.com/1190916/39863962-81d6fea4-5448-11e8-81fa-e69bb2f5d0c6.png">

Make sure that it's set to one of these three: "Sonoff 4CH", "4 Channel" or "Sonoff 4CH Pro".

**Comment by robertklep** [comment]
Oh, a quick way to the settings page, provided you're running the latest beta version of my app, is through (Homey) Settings > Sonoff:

<img width="686" alt="screen shot 2018-05-10 at 11 53 27" src="https://user-images.githubusercontent.com/1190916/39864075-d8f9a25e-5448-11e8-9672-d1536984fdda.png">

Clicking on the IP-address will open the Tasmota configuration page for the device.

**Comment by LyoshaDovolen** [comment]
Thank you Robert . I'll try this later

**Comment by robertklep** [comment]
@LyoshaDovolen to be clear: you _do_ receive the push notification?

**Comment by LyoshaDovolen** [comment]
yes. (notification for flow check)

**Comment by robertklep** [comment]
Do you know how to use an MQTT client? I'd like to see what the Homey app is sending to the MQTT broker when the flow is being run.

**Comment by LyoshaDovolen** [comment]
when the flow is being run - nothing happens in [log](https://pp.userapi.com/c847123/v847123539/75ea6/O7tgvi45ElI.jpg)

**Comment by robertklep** [comment]
That's certainly not how it's supposed to work. I'll check and see what's going on.

**Comment by robertklep** [comment]
Yeah, it's a bug. Will fix ASAP.

**Comment by robertklep** [comment]
I just submitted v4.0.8 to the Homey app store for review, which should fix this problem.

**Comment by robertklep** [comment]
v4.0.8 was just published, please check and see if it works better :D

**Comment by LyoshaDovolen** [comment]
Everything works fine now. Thank you Robert

**Comment by robertklep** [comment]
Thanks for testing!
